---
title: "CoC Data EDA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CoC Data EDA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(targets)
library(hrbrthemes)
library(tidyverse)
library(here)
library(showtext)
library(DataExplorer)
library(kableExtra)
library(corrr)
library(ggiraph)
library(glue)

font_add_google("Libre Franklin", family = "libre franklin")
showtext_auto()

base_theme <- theme_minimal(base_family = "libre franklin") +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "grey90")
  )

knitr::opts_chunk$set(
  fig.showtext = TRUE,
  echo = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r load data, include = FALSE}
# for this chunk only set wd to project root so targets can find everything it
# needs to validate and load the data
setwd(here())

# a function that stops the document knitting if the target is outdated
check_outdated <- function(target, outdated = tar_outdated()) {
  assertthat::assert_that(
    !(target %in% outdated),
    msg = paste(target, "is out of date, run tar_make() or tar_make_future() to update it")
  )
}
targets <- c("summary_stats", "combined_dataset")
purrr::walk(targets, check_outdated, outdated = tar_outdated())

tar_load(all_of(targets))
```

## Data Introduction

```{r intro table}
introduce(combined_dataset) %>%
  mutate(memory_usage = round(memory_usage / 1000, 0)) %>%
  rename(`memory_usage_(kb)` = memory_usage) %>%
  pivot_longer(everything(), names_to = "stat", values_to = "value") %>%
  mutate(
    stat = str_replace_all(stat, "_", " "),
    stat = str_to_sentence(stat)
  ) %>%
  kbl(
    col.names = c("", ""),
    format.args = list(big.mark = ",")
  ) %>%
  kable_styling()
```

## Summary Statistics
```{r summary_stats_table}
summary_stats %>%
  select(-c(N, `10th`, `90th`, `99th`)) %>%
  # align first column (variable name) left and all others (values) right
  kbl(align = c("l", rep("r", ncol(.) - 1))) %>%
  kable_styling(
    bootstrap_options = c("striped")
  ) %>%
  add_header_above(c(" " = 6, "Percentiles" = 2))
```
The observations with missing homelessness counts and rates are from CoCs that did not conduct a PiT count in a given year or result from the "shared jurisdiction" Massachusetts CoC which is present in the shapefiles but not in the PiT count data.

## Correlation with Homelessness Rate
```{r correlations, include=FALSE}
correlation_dataset <- combined_dataset %>%
  select(where(is.numeric), -eviction_filing_rate, -starts_with("homeless_rate"), -fmr1_pct_coc_na_rent, -fmr2_pct_coc_na_rent, -fmr3_pct_coc_na_rent, -fmr4_pct_coc_na_rent) %>%
  correlate()
```

```{r corr with homelessness, fig.height=7}
homelessness_rate_correlation_plot <- correlation_dataset %>%
  focus(homeless_per_1000_total_pop) %>%
  filter(!str_detect(term, "homeless")) %>%
  mutate(
    pos_neg = homeless_per_1000_total_pop >= 0,
    tt = round(homeless_per_1000_total_pop, 2)
  ) %>%
  ggplot() +
  geom_bar_interactive(
    aes(x = term, y = homeless_per_1000_total_pop, fill = pos_neg, tooltip = tt),
    stat = "identity",
    width = 0.6
  ) +
  scale_fill_manual(
    guide = "none",
    values = c("TRUE" = "#d7191c", "FALSE" = "#1a9641")
  ) +
  ylim(c(-0.5, 0.5)) +
  labs(
    subtitle = "Correlation coefficient with homeless_per_1000_total_pop",
    x = NULL,
    y = NULL
  ) +
  coord_flip() +
  base_theme +
  theme(plot.title.position = "plot")

girafe(ggobj = homelessness_rate_correlation_plot, height_svg = 7)
```




combined_dataset %>% 
```
