---
title: "Summary Stats"
output: rmarkdown::html_vignette
full_width_article: true
vignette: >
  %\VignetteIndexEntry{Summary Stats}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE
)
options(tidyverse.quiet = TRUE)

library(kableExtra)
library(targets)
library(here)

```

```{r load data, include = FALSE}
# for this chunk only set wd to project root so targets can find everything it
# needs to validate and load the data
setwd(here())

targets = c("summary_stats", "shapefile_years")

check_outdated = function(target, outdated = tar_outdated()) {
  assertthat::assert_that(
    !(target %in% outdated),
    msg = paste(target, "is out of date, run tar_make() or tar_make_future() to update it")
  )
}
purrr::walk(targets, check_outdated, outdated = tar_outdated())

tar_load(all_of(targets))
```

### Years: `r min(shapefile_years)`-`r max(shapefile_years)`

```{r summary stats}
summary_stats %>% 
  # align first column (variable name) left and all others (values) right
  kbl(align = c("l", rep("r", ncol(.) - 1))) %>% 
  kable_styling(
    bootstrap_options = c("striped"),
    fixed_thead = TRUE
  ) %>% 
  add_header_above(c(" " = 7, "Percentiles" = 5))
```

The observations with missing homelessness counts and rates are from CoCs that did not conduct a PiT count in a given year or result from the "shared jurisdiction" Massachusetts CoC which is present in the shapefiles but not in the PiT count data.
