on:
  push:
    branches:
      - main
      - master
      - test-ci-data-build
    tags:
      -'*'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          restore-keys: |

      - name: Install dependencies
        run: |
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .
        
      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
